atom_feed:
  name: My Menki Blog
  subtitle: Catchy catch phrase
  author:
    name: The Menkster
    email: menkster@menkilicious.com

admin_open_id_urls:
  - http://menkiblog.com

default_post_format: markdown
